server:
  servlet:
    context-path: /my-app
  port: 8480

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/purchase?stringtype=unspecified
    username: postgres
    password: root
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
            ddl-auto: update



  flyway:
    baseline-on-migrate: true

#jwt:
#  header: Authorization
#  secret: swecor
#  expiration: 31536000




